"""Build the five-page Efy website preview with shared navigation and FAQ data."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'public' / 'nueva'
OUT.mkdir(exist_ok=True)
ARROW = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>'
FAQ = [
    {'id':'elegir','category':'Antes de elegir','question':'¿Por dónde empiezo para elegir un seguro?','answer':'Empieza por lo que quieres proteger y por los riesgos que te preocupan. Después compara coberturas, exclusiones, deducibles, límites y costo. Una propuesta debe ayudarte a entender qué incluye y qué queda fuera.'},
    {'id':'cotizar','category':'Antes de elegir','question':'¿Qué información preparo para pedir una cotización?','answer':'Anota qué quieres proteger, qué cobertura buscas y las preguntas que necesitas resolver. Los datos y documentos necesarios dependen del tipo de seguro y de la aseguradora. Confirma los requisitos por un canal oficial antes de enviar información personal.'},
    {'id':'cobertura','category':'Tu póliza','question':'¿Qué es una cobertura?','answer':'Es la protección que la póliza ofrece para un riesgo o una situación determinada. Su alcance depende de las condiciones, los límites y las exclusiones que aparecen en el contrato.'},
    {'id':'deducible','category':'Tu póliza','question':'¿Qué significa deducible?','answer':'Es la parte del costo de un evento cubierto que corresponde asumir al asegurado, cuando así lo establece la póliza. Puede expresarse como un valor, un porcentaje o una combinación. Revisa cuándo se aplica y cómo se calcula.'},
    {'id':'exclusiones','category':'Tu póliza','question':'¿Qué son las exclusiones?','answer':'Son las situaciones o los riesgos que la póliza no cubre. Antes de elegir, revisa las exclusiones junto con las coberturas y pregunta por cualquier condición que no entiendas.'},
    {'id':'renovar','category':'Tu póliza','question':'¿Qué reviso antes de renovar mi seguro?','answer':'Comprueba la fecha de vencimiento, las coberturas, los límites, los deducibles, el costo y los cambios en tus necesidades. Confirma las condiciones de la nueva vigencia antes de aceptarla.'},
    {'id':'siniestro','category':'Si ocurre un evento','question':'¿Qué hago si necesito reportar un siniestro?','answer':'Prioriza tu seguridad. Si hay una emergencia, llama al 911 en Ecuador. Puedes informar a Efy desde el módulo Siniestros; el reporte se envía a siniestros@efyseguros.com. También debes seguir los canales y plazos de tu aseguradora indicados en la póliza. Este aviso a Efy no confirma cobertura ni sustituye el aviso exigido por la aseguradora.'},
    {'id':'documentos','category':'Si ocurre un evento','question':'¿Dónde encuentro los canales de asistencia de mi seguro?','answer':'Consulta tu póliza, certificado o documentación de la aseguradora. Allí debes verificar los teléfonos y el procedimiento aplicable. La guía de EVIA no recibe reportes ni reemplaza los canales de asistencia de tu aseguradora.'},
    {'id':'ubicacion','category':'Sobre Efy','question':'¿Dónde está Efy?','answer':'Efy está en Quito. La dirección y los canales oficiales de atención se incorporarán cuando estén confirmados.'},
    {'id':'contacto','category':'Sobre Efy','question':'¿Cómo puedo contactar a Efy?','answer':'Estamos preparando los canales oficiales de contacto, incluido WhatsApp. Mientras tanto, puedes consultar esta guía o preparar tu consulta en el módulo Contactos. EVIA no envía mensajes ni solicitudes al equipo.'},
    {'id':'evia','category':'Sobre Efy','question':'¿Quién es EVIA y cómo funciona este chat?','answer':'EVIA es la guía digital de esta web. Este chat responde a partir de las preguntas frecuentes de Efy: ofrece información general y te ayuda a preparar preguntas. No consulta pólizas, no cotiza y no confirma coberturas particulares.'},
]

home = f'''
<section class="home-hero" aria-labelledby="page-title">
  <figure class="workshop" aria-hidden="true">
    <picture><source media="(max-width:760px)" srcset="../assets/evia-workshop-mobile.webp?v=evia-wide-restored-20261009"><img src="../assets/evia-workshop.webp?v=evia-wide-restored-20261009" alt="" width="1280" height="720" fetchpriority="high"></picture>
    <video class="workshop-video" muted playsinline loop preload="none" tabindex="-1"></video><div class="workshop-shade"></div>
  </figure>
  <div class="container hero-copy">
    <p class="eyebrow light">EFY SEGUROS · TU MEJOR ELECCIÓN</p>
    <h1 id="page-title">Elegir bien.<br>Vivir con<br><span>tranquilidad.</span></h1>
    <p class="hero-lead">Elegir un seguro empieza por entenderlo.<br>Conoce Efy y encuentra el próximo paso para ti.</p>
    <div class="actions"><a class="button primary" href="nosotros.html">Conoce Efy {ARROW}</a><button class="button ghost" type="button" data-open-chat>Habla con EVIA</button></div>
    <p class="hero-note">Una nueva experiencia de Efy, desde Quito.</p>
  </div>
  <p class="scene-note"><span></span>EVIA, dando forma a nuestro universo digital.</p>
</section>
<section class="section container" aria-labelledby="start-title">
  <div class="section-heading"><p class="eyebrow">A TU RITMO</p><h2 id="start-title">La información que necesitas.<br><span>Un lugar para encontrarla.</span></h2></div>
  <div class="editorial-links">
    <a class="editorial-link" href="nosotros.html"><div><p class="small-label">NOSOTROS</p><h3>Conoce el mundo de Efy.</h3><p>Nuestra identidad, lo que nos mueve y EVIA, nuestra guía digital.</p></div>{ARROW}</a>
    <a class="editorial-link" href="ayuda.html"><div><p class="small-label">AYUDA</p><h3>Entiende antes de decidir.</h3><p>Respuestas sobre coberturas, deducibles y conceptos de tu póliza.</p></div>{ARROW}</a>
    <a class="editorial-link" href="siniestros.html"><div><p class="small-label">SINIESTROS</p><h3>Reporta lo ocurrido.</h3><p>Envía los datos del evento y sus adjuntos al equipo de siniestros de Efy.</p></div>{ARROW}</a>
    <a class="editorial-link" href="contactos.html"><div><p class="small-label">CONTACTOS</p><h3>Encuentra tu siguiente paso.</h3><p>Prepara tus preguntas y conoce los canales de atención de Efy.</p></div>{ARROW}</a>
  </div>
</section>
<section class="guide-section"><div class="container guide-grid"><div><p class="eyebrow light">CONOCE A EVIA</p><h2>Una guía cercana.<br><span>Para preguntas reales.</span></h2><p>EVIA te ayuda a encontrar información general sobre seguros y a organizar lo que quieres consultar.</p><button class="button primary" type="button" data-open-chat>Iniciar una conversación {ARROW}</button></div><div class="chat-preview"><div class="avatar-row"><img src="../assets/site/evia-portrait.jpg" alt="" width="56" height="56" loading="lazy"><div><strong>EVIA</strong><span>Guía de preguntas frecuentes</span></div></div><p class="preview-message">Hola, soy EVIA. ¿Qué te gustaría entender mejor?</p><button type="button" class="suggestion" data-chat-question="¿Qué significa deducible?">¿Qué significa deducible? {ARROW}</button><button type="button" class="suggestion" data-chat-question="¿Por dónde empiezo para elegir un seguro?">¿Por dónde empiezo? {ARROW}</button></div></div></section>
'''

about = f'''
<section class="about-hero"><div class="container about-grid"><div><p class="eyebrow light">NOSOTROS</p><h1 id="page-title">Efy Seguros.<br><span>Tu mejor elección.</span></h1><p class="large-copy">Una marca con una idea clara: acercarte al mundo de los seguros con información sencilla y una experiencia más cercana.</p><p class="location-line"><span class="location-dot"></span>Desde Quito.</p></div><figure class="portrait-panel"><img src="../assets/site/evia-portrait.jpg" alt="EVIA, astronauta de traje crema con detalles rosados y el nombre EVIA en el pecho" width="960" height="1280" fetchpriority="high"><figcaption><span>EVIA</span>Una nueva forma de acompañarte.</figcaption></figure></div></section>
<section class="section container" aria-labelledby="principles-title"><div class="section-heading"><p class="eyebrow">LO QUE NOS MUEVE</p><h2 id="principles-title">Más claridad.<br><span>Más cerca de ti.</span></h2></div><div class="principles"><article><h3>Entender primero.</h3><p>Una decisión empieza con preguntas. Queremos que los conceptos sean claros y que sepas qué revisar antes de elegir.</p></article><article><h3>Hablar sencillo.</h3><p>Explicar coberturas, condiciones y exclusiones con palabras que puedas reconocer en tu día a día.</p></article><article><h3>Acompañar con propósito.</h3><p>Crear un espacio útil para conocer Efy, resolver dudas generales y preparar tu siguiente consulta.</p></article></div></section>
<section class="soft-section"><div class="container story-grid"><p class="eyebrow">NUESTRO UNIVERSO DIGITAL</p><div><h2>EVIA abre la conversación.</h2><p class="large-copy">Nuestra astronauta representa la curiosidad de explorar, construir y encontrar respuestas. En esta web, te orienta entre las preguntas frecuentes.</p><p>El chat ofrece información general. Las condiciones de cada seguro se revisan en su póliza y con la aseguradora correspondiente.</p><a class="text-link" href="ayuda.html">Explora el centro de ayuda {ARROW}</a></div></div></section>
'''

contact = f'''
<section class="page-intro container"><p class="eyebrow">CONTACTOS</p><h1 id="page-title">Toda conversación<br>empieza con <span>una pregunta.</span></h1><p class="large-copy intro-copy">Cuéntale a EVIA qué te gustaría entender o prepara tus preguntas para Efy.</p></section>
<section class="container contact-grid" aria-label="Orientación y contacto"><div class="contact-info"><p class="small-label">ESTAMOS EN</p><h2>Quito.</h2><p>Los canales oficiales de atención y WhatsApp se incorporarán próximamente.</p><div class="contact-rule"></div><p class="small-label">ANTES DE CONSULTAR</p><p>Ten a mano el tema que quieres resolver y las preguntas que necesitas hacer. Los requisitos de una cotización dependen del seguro y de la aseguradora.</p><a class="text-link" href="ayuda.html">Ver preguntas frecuentes {ARROW}</a></div><div class="contact-chat"><div class="avatar-row"><img src="../assets/site/evia-portrait.jpg" alt="" width="56" height="56"><div><strong>Conversa con EVIA</strong><span>Guía de Efy</span></div></div><h2>Empecemos<br>por lo que necesitas.</h2><p>Información general sobre seguros, conceptos de tu póliza y cómo preparar una consulta.</p><button class="button primary" type="button" data-open-chat>Abrir el chat {ARROW}</button><p class="fine-print">EVIA responde con la guía de preguntas frecuentes. No recibe reportes ni envía solicitudes al equipo.</p></div></section>
<section class="section container consult-section" aria-labelledby="consult-title"><div><p class="eyebrow">PREPARA TU CONSULTA</p><h2 id="consult-title">Ordena tus ideas.<br><span>Lleva las preguntas claras.</span></h2><p>Escribe qué necesitas y genera un resumen que puedas copiar para tu próxima conversación.</p></div><form id="consult-form"><label for="consult-topic">¿Sobre qué quieres consultar?</label><select id="consult-topic" name="topic" required><option value="">Selecciona un tema</option><option>Elegir un seguro</option><option>Solicitar información para una cotización</option><option>Entender mi póliza</option><option>Consultar una renovación</option><option>Otra consulta</option></select><label for="consult-question">¿Qué te gustaría saber?</label><textarea id="consult-question" name="question" rows="4" maxlength="1200" required placeholder="Por ejemplo: quiero saber qué revisar al comparar dos propuestas."></textarea><p class="form-hint">El resumen se prepara aquí, sin enviarlo ni guardarlo. Evita incluir datos personales.</p><button class="button blue" type="submit">Preparar mi consulta {ARROW}</button><div id="consult-result" class="consult-result" hidden><label for="consult-summary">Tu consulta preparada</label><textarea id="consult-summary" rows="5" readonly></textarea><button class="text-link" type="button" id="copy-consult">Copiar consulta {ARROW}</button><p id="copy-status" role="status"></p></div></form></section>
'''

categories = ['Todas', 'Antes de elegir', 'Tu póliza', 'Si ocurre un evento', 'Sobre Efy']
filters = ''.join(f'<button class="filter-button" type="button" data-category="{c}" aria-pressed="{str(i==0).lower()}">{c}</button>' for i,c in enumerate(categories))
faq_rows = ''.join(f'<details class="faq-item" data-category="{f["category"]}" id="faq-{f["id"]}"><summary>{f["question"]}<span aria-hidden="true"></span></summary><div><p class="faq-category">{f["category"]}</p><p>{f["answer"]}</p></div></details>' for f in FAQ)
help_page = f'''
<section class="help-intro container"><p class="eyebrow">AYUDA</p><h1 id="page-title">Las buenas decisiones<br>empiezan con <span>claridad.</span></h1><p class="large-copy">Encuentra respuestas sobre seguros y sobre Efy.</p><form class="faq-search" role="search"><label class="sr-only" for="faq-search">Buscar en preguntas frecuentes</label><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="faq-search" type="search" placeholder="Busca: cobertura, deducible, renovación…" autocomplete="off"><button type="button" id="clear-search" hidden aria-label="Borrar búsqueda">×</button></form></section>
<section class="container help-content" aria-label="Preguntas frecuentes"><div class="faq-filters" aria-label="Filtrar preguntas por tema">{filters}</div><p class="search-status" id="search-status" role="status">{len(FAQ)} preguntas para orientarte</p><div class="faq-list">{faq_rows}</div><div class="no-results" id="no-results" hidden><h2>No encontramos esa pregunta.</h2><p>Prueba con una palabra más breve, como «póliza» o «cobertura», o conversa con EVIA.</p><button class="button blue" type="button" data-open-chat>Consultar a EVIA {ARROW}</button></div><p class="help-disclaimer">Información general. Las coberturas, requisitos y procedimientos dependen de las condiciones de cada póliza y aseguradora.</p></section>
<section class="soft-section"><div class="container help-cta"><div><p class="eyebrow">UNA PREGUNTA MÁS</p><h2>EVIA también puede orientarte.</h2><p>Conversa con nuestra guía o prepara una consulta para Efy.</p></div><div class="actions"><button class="button blue" type="button" data-open-chat>Abrir el chat {ARROW}</button><a class="text-link" href="contactos.html">Ir a Contactos {ARROW}</a></div></div></section>
'''


claim_page = f'''
<section class="page-intro container claim-intro"><p class="eyebrow">SINIESTROS</p><h1 id="page-title">Cuéntanos lo ocurrido.<br><span>Empecemos por ayudarte.</span></h1><p class="large-copy intro-copy">Envía tu reporte al equipo de Efy. Te pediremos los datos del evento y una forma de contactarte.</p><div class="actions claim-start"><a class="button blue" href="#claim-workspace">Comenzar reporte {ARROW}</a></div></section>
<section class="container claim-layout" aria-label="Reporte de siniestro"><aside class="claim-guide"><div class="urgent-note"><p class="small-label">SI HAY UNA EMERGENCIA</p><h2>Tu seguridad<br>es lo primero.</h2><p>En Ecuador, llama al <a href="tel:911">911</a> si necesitas atención urgente. Este formulario no ofrece asistencia inmediata.</p></div><div class="claim-destination"><p class="small-label">TU REPORTE LLEGARÁ A</p><a href="mailto:siniestros@efyseguros.com">siniestros@efyseguros.com</a><p>El envío informa a Efy. Revisa también los canales y plazos de aviso exigidos por tu aseguradora.</p></div><p class="claim-note">La referencia que recibas corresponde al reporte para Efy; no confirma cobertura, indemnización ni aceptación por la aseguradora.</p><a class="text-link" href="ayuda.html#faq-siniestro">Revisa nuestra guía de siniestros {ARROW}</a></aside>
<div class="claim-workspace" id="claim-workspace" tabindex="-1"><ol class="claim-progress" aria-label="Pasos del reporte"><li aria-current="step"><span>1</span>Tu contacto</li><li><span>2</span>El evento</li><li><span>3</span>Revisar y enviar</li></ol><p id="claim-availability" class="form-hint" role="status">Comprobando disponibilidad del envío…</p><div id="claim-error" class="claim-error" role="alert" hidden></div>
<noscript><p class="claim-error">Para completar el formulario, activa JavaScript. También puedes enviar tu reporte a <a href="mailto:siniestros@efyseguros.com">siniestros@efyseguros.com</a>.</p></noscript>
<form id="claim-form" enctype="multipart/form-data" method="post" action="api/siniestros.php">
<fieldset class="claim-step" data-step="0"><legend>¿Cómo podemos contactarte?</legend><p class="step-intro">Estos datos permiten que el equipo de Efy identifique tu reporte y pueda comunicarse contigo.</p><label for="claim-name">Nombre y apellido <span class="required-label">(obligatorio)</span></label><input id="claim-name" name="name" autocomplete="name" minlength="2" maxlength="120" required><div class="claim-fields"><div><label for="claim-phone">Teléfono <span class="required-label">(obligatorio)</span></label><input id="claim-phone" name="phone" type="tel" autocomplete="tel" inputmode="tel" maxlength="25" placeholder="Ej.: +593 99 123 4567" required></div><div><label for="claim-email">Correo electrónico <span class="required-label">(opcional)</span></label><input id="claim-email" name="email" type="email" autocomplete="email" maxlength="254" placeholder="tu@correo.com"></div></div><div class="claim-fields"><div><label for="claim-insurer">Aseguradora <span class="required-label">(opcional)</span></label><input id="claim-insurer" name="insurer" maxlength="100" placeholder="Si la conoces"></div><div><label for="claim-policy">Número de póliza <span class="required-label">(opcional)</span></label><input id="claim-policy" name="policy" maxlength="100" placeholder="Si lo tienes a mano"></div></div><div class="step-actions"><button class="button blue" type="button" data-claim-next>Continuar {ARROW}</button></div></fieldset>
<fieldset class="claim-step" data-step="1"><legend>¿Qué ocurrió?</legend><p class="step-intro">Describe los hechos con tus palabras. Puedes adjuntar fotos o documentos que ayuden a entender el evento.</p><label for="claim-type">Tipo de evento <span class="required-label">(obligatorio)</span></label><select id="claim-type" name="event_type" required><option value="">Selecciona una opción</option><option>Accidente</option><option>Daños</option><option>Robo</option><option>Otro evento</option></select><div class="claim-fields"><div><label for="claim-date">Fecha del evento <span class="required-label">(obligatorio)</span></label><input id="claim-date" name="event_date" type="date" required></div><div><label for="claim-time">Hora aproximada <span class="required-label">(opcional)</span></label><input id="claim-time" name="event_time" type="time"><p class="form-hint">Hora de Quito.</p></div></div><label for="claim-location">Lugar del evento <span class="required-label">(obligatorio)</span></label><input id="claim-location" name="location" maxlength="240" placeholder="Ciudad y dirección o referencia" required><label for="claim-description">Describe lo ocurrido <span class="required-label">(obligatorio)</span></label><textarea id="claim-description" name="description" rows="5" minlength="20" maxlength="4000" required placeholder="Indica qué pasó y qué daños observaste."></textarea><p class="form-hint">Incluye sólo información necesaria para el reporte. No escribas claves, datos bancarios ni detalles médicos.</p><label for="claim-files">Fotos o documentos <span class="required-label">(opcional)</span></label><input id="claim-files" name="attachments[]" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" multiple aria-describedby="claim-file-hint"><p id="claim-file-hint" class="form-hint">Hasta 3 archivos JPG, PNG, WebP o PDF. Máximo 2 MB por archivo.</p><ul id="claim-file-list" class="claim-file-list" aria-label="Archivos seleccionados"></ul><div class="step-actions"><button class="text-link" type="button" data-claim-back>Volver</button><button class="button blue" type="button" data-claim-next>Revisar reporte {ARROW}</button></div></fieldset>
<fieldset class="claim-step" data-step="2"><legend>Revisa antes de enviar.</legend><p class="step-intro">Comprueba los datos. Tu reporte se enviará a <strong>siniestros@efyseguros.com</strong>.</p><dl id="claim-review" class="claim-review"></dl><label class="claim-consent" for="claim-consent"><input id="claim-consent" name="consent" type="checkbox" value="1" required><span>Autorizo a Efy a usar la información y los adjuntos de este reporte para gestionar mi caso y contactarme.</span></label><p class="form-hint">Los datos se envían al correo del equipo de siniestros. Los adjuntos no se publican en la web. Este aviso no sustituye los procedimientos de la aseguradora.</p><div class="step-actions"><button class="text-link" type="button" data-claim-back>Corregir datos</button><button id="claim-send" class="button blue" type="submit" disabled>Enviar reporte {ARROW}</button></div></fieldset><div class="claim-honeypot" aria-hidden="true"><label for="claim-website">Sitio web</label><input id="claim-website" name="website" tabindex="-1" autocomplete="off"></div></form>
<section id="claim-success" class="claim-success" aria-labelledby="claim-success-title" hidden><div class="receipt-icon" aria-hidden="true">✓</div><p class="eyebrow">REPORTE PARA EFY</p><h2 id="claim-success-title">Tu reporte fue enviado.</h2><p>El servidor aceptó el envío a <strong>siniestros@efyseguros.com</strong>. Conserva esta referencia para consultar al equipo.</p><p class="receipt-reference" id="claim-reference"></p><p class="form-hint" id="claim-received-at"></p><p class="claim-note">Esta referencia no es un número de siniestro emitido por la aseguradora ni confirma cobertura. Sigue también sus instrucciones de aviso.</p><div class="actions"><button id="claim-download" type="button" class="button blue">Descargar comprobante {ARROW}</button><a class="text-link" href="index.html">Volver al inicio</a></div></section></div></section>
'''

pages = [
    ('index.html','Inicio','Efy Seguros · Tu mejor elección',home),
    ('contactos.html','Contactos','Contactos · Efy Seguros',contact),
    ('nosotros.html','Nosotros','Nosotros · Efy Seguros',about),
    ('ayuda.html','Ayuda','Ayuda · Efy Seguros',help_page),
    ('siniestros.html','Siniestros','Reportar un siniestro · Efy Seguros',claim_page),
]
for filename, label, title, content in pages:
    nav = ''.join(f'<a href="{file}"'+(' aria-current="page"' if file==filename else '')+f'>{name}</a>' for file,name,_,_ in pages)
    footer_links = ''.join(f'<a href="{file}">{name}</a>' for file,name,_,_ in pages)
    document = f'''<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#080e1d"><meta name="description" content="Conoce Efy Seguros, encuentra información útil y conversa con EVIA, nuestra guía de preguntas frecuentes."><title>{title}</title><link rel="icon" href="../assets/efy-seguros-transparent.png" type="image/png"><link rel="preload" href="../assets/fonts/nunito-sans-latin-700-normal.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="../assets/site/efy-site.css?v=claims-20261009"><script src="../assets/site/efy-site.js?v=claims-20261009" defer></script></head>
<body data-page="{label.lower()}"><a class="skip-link" href="#contenido">Ir al contenido</a>
<header class="site-header"><div class="container header-inner"><a class="brand" href="index.html" aria-label="Efy Seguros, Inicio"><img src="../assets/efy-seguros-transparent.png" alt="Efy Seguros · Tu mejor elección" width="1774" height="887"></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav"><span>Menú</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button><nav id="site-nav" class="site-nav" aria-label="Navegación principal">{nav}</nav><button class="header-chat" type="button" data-open-chat>Conversa con EVIA {ARROW}</button></div></header>
<main id="contenido">{content}</main>
<footer class="site-footer"><div class="container"><div class="footer-top"><a class="brand" href="index.html"><img src="../assets/efy-seguros-transparent.png" alt="Efy Seguros" width="1774" height="887" loading="lazy"></a><nav aria-label="Navegación del pie de página">{footer_links}</nav><p>Desde Quito.<br>Una nueva experiencia de Efy.</p></div><div class="footer-bottom"><p>© 2026 Efy Seguros.</p><span>Tu mejor elección.</span></div></div></footer>
<button class="chat-fab" type="button" data-open-chat aria-controls="evia-dialog" aria-expanded="false"><img src="../assets/site/evia-portrait.jpg" alt="" width="40" height="40"><span>Habla con EVIA</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M20 11.5a8 8 0 0 1-8 8H5l-3 3V11.5a9 9 0 0 1 18 0Z"/></svg></button>
<dialog id="evia-dialog" class="evia-dialog" aria-labelledby="chat-title"><div class="chat-header"><div class="avatar-row"><img src="../assets/site/evia-portrait.jpg" alt="" width="44" height="44"><div><h2 id="chat-title">EVIA</h2><span>Guía de preguntas frecuentes</span></div></div><button id="close-chat" class="icon-button" type="button" aria-label="Cerrar chat">×</button></div><p class="chat-context">Información general de seguros. Evita compartir datos personales.</p><div id="chat-messages" class="chat-messages" role="log" aria-live="polite" aria-relevant="additions" aria-label="Conversación con EVIA"><div class="chat-message bot"><span>EVIA</span><p>Hola, soy EVIA. Puedo orientarte con las preguntas frecuentes de Efy. ¿Qué te gustaría conocer?</p></div></div><div class="chat-suggestions"><button type="button" data-chat-question="¿Qué significa deducible?">Deducibles</button><button type="button" data-chat-question="¿Por dónde empiezo para elegir un seguro?">Elegir un seguro</button><button type="button" data-chat-question="¿Cómo puedo contactar a Efy?">Contactar a Efy</button></div><form id="chat-form" class="chat-form"><label class="sr-only" for="chat-input">Tu pregunta para EVIA</label><input id="chat-input" type="text" maxlength="400" placeholder="Escribe tu pregunta…" autocomplete="off" required><button class="icon-button send-button" type="submit" aria-label="Enviar pregunta a EVIA">{ARROW}</button></form><a class="chat-help-link" href="ayuda.html">Ver todas las preguntas frecuentes {ARROW}</a></dialog>
<script id="faq-data" type="application/json">{json.dumps(FAQ,ensure_ascii=False).replace('<','\\u003c')}</script>
</body></html>'''
    if filename == 'siniestros.html':
        document = document.replace('</head>', '<script src="../assets/site/siniestros.js?v=claims-20261009" defer></script></head>')
    document = re.sub(r'(<img src="../assets/site/evia-portrait.jpg" alt=""[^>]*>)', r'<span class="evia-avatar">\1</span>', document)
    document = document.replace('</head>', '<noscript><style>button[data-open-chat],.suggestion,.faq-search,.faq-filters,#search-status,#consult-form,#claim-form,.claim-progress,#claim-availability{display:none}</style></noscript></head>')
    (OUT / filename).write_text(document)
    print('Built', filename)
